#include "IMU_config.h"

#define IMU_GYRO_CALIB_SAMPLE_SIZE 250

#define IMU_ACCEL_ENABLE
#define IMU_ACCEL_COEFF 0.01

#define I2C_SPEED 400000

#define SKETCH_VECTOR_OUTPUT
#define SKETCH_FRAME_DROP 25
