#define PPMRX_CHANNELS 6

#define PPMRX_CHANNEL_THROTTLE 4
#define PPMRX_CHANNEL_RUDDER 5
#define PPMRX_CHANNEL_ELEVATOR 3
#define PPMRX_CHANNEL_AILERONS 0
#define PPMRX_CHANNEL_GEAR 2
#define PPMRX_CHANNEL_AUX 1
